export const getDummies = () => [
  {
    id: 1,
    title: '테스트 제목 입니다 1 user01',
    content: '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 2,
    title: '테스트 제목 입니다 2 user02',
    content:
      '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n 테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user02',
  },
  {
    id: 3,
    title: '테스트 제목 입니다 3 user01',
    content: '?',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 4,
    title: '테스트 제목 입니다 테스트 제목 입니다. user03',
    content: '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user03',
  },
  {
    id: 5,
    title: '테스트 제목 입니다 user01',
    content:
      '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 6,
    title: '테스트 제목 입니다 1 user02',
    content: '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user02',
  },
  {
    id: 7,
    title: '테스트 제목 입니다 2 user01',
    content:
      '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n 테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 8,
    title: '테스트 제목 입니다 3 user01',
    content: '?',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 9,
    title:
      'user01 테스트 제목 입니다 테스트 제목 입니다 테스트 제목 입니다 테스트 제목 입니다 테스트 제목 입니다 테스트 제목 입니다.. ',
    content: '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
  {
    id: 10,
    title: 'user01 테스트 제목 입니다',
    content:
      '테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요테스트 내용 테스트 내용 저녁 뭐먹지 추천 부탁드려요\n',
    created_at: new Date(),
    views: 10,
    likes: 1,
    comments: 10,
    user_id: 'user01',
  },
];

export const getCommentsDummies = [
  {
    id: 1,
    user_id: 'user01',
    content: '댓글 답니다',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 2,
    user_id: 'user02',
    content: '댓글 답니다요 2',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 3,
    user_id: 'user02',
    content: '댓글을 한번 테스트용으로 달기 배고프다 저녁 메뉴 추천은 돈까스',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 4,
    user_id: 'user02',
    content: '댓글 답니다요 2',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 5,
    user_id: 'user02',
    content: '댓글을 한번 테스트용으로 달기 배고프다 저녁 메뉴 추천은 돈까스',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 6,
    user_id: 'user02',
    content: '댓글을 한번 테스트용으로 달기 배고프다 저녁 메뉴 추천은 돈까스',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 7,
    user_id: 'user02',
    content: '댓글 답니다요 2',
    created_at: new Date(),
    likes: 1,
  },
  {
    id: 8,
    user_id: 'user02',
    content: '댓글을 한번 테스트용으로 달기 배고프다 저녁 메뉴 추천은 돈까스',
    created_at: new Date(),
    likes: 1,
  },
];
